// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89IRBkfZmYLWSWDlpahiijkJ1bVkRRqY',
    appId: '1:1052196018004:web:c721b00d5f2c6a54549ac1',
    messagingSenderId: '1052196018004',
    projectId: 'coconut-disease-detectio-de81f',
    authDomain: 'coconut-disease-detectio-de81f.firebaseapp.com',
    storageBucket: 'coconut-disease-detectio-de81f.appspot.com',
    measurementId: 'G-7YEN3M0QHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCIZkDVuTajtrw9EbuaY46cQCY6RnGYw',
    appId: '1:1052196018004:android:fb2d2c029d62ea73549ac1',
    messagingSenderId: '1052196018004',
    projectId: 'coconut-disease-detectio-de81f',
    storageBucket: 'coconut-disease-detectio-de81f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnApdfXyrXdZFlyb2dsikYSjfNeHxLxso',
    appId: '1:1052196018004:ios:1061758efb66382f549ac1',
    messagingSenderId: '1052196018004',
    projectId: 'coconut-disease-detectio-de81f',
    storageBucket: 'coconut-disease-detectio-de81f.appspot.com',
    iosBundleId: 'com.example.coconutDiseaseDetection',
  );
}
